name: Format with Laravel Pint
on:
  push:
   branches:
      - "*"
  pull_request:
    branches: 
      - "*"
jobs:
  format:
 # Check if the PR is not from a fork
    if: github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Run Pint formatter
        run: vendor/bin/pint
      - name: Check for modified files
        id: git-check
        run: echo "modified=$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi)" >> $GITHUB_OUTPUT
      - name: Push changes
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --global user.name 'Owiesnama'
          git config --global user.email 'owiesnama@users.noreply.github.com'
          git commit -am "formating: laravel pint"
          git push
